language: node_js
sudo: false
node_js:
  - "0.12"
  - "4"
  - "5"

cache:
  directories:
    - node_modules

install:
  - bash ./build/ci/install.sh

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bash ./build/ci/test.sh
