language: node_js
sudo: false
node_js:
  - "0.12"
  - "4"
  - "5"

cache:
  directories:
    - node_modules

install:
  # Check the size of caches
  - du -sh ./node_modules || true
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  - npm install -g npm@2.5
  # Instal npm dependecies and ensure that npm cache is not stale
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bash ./build/ci.sh
