language: node_js
sudo: false
node_js:
  - "0.12"
  - "4"
  - "5"

branches:
  only:
    - master
    - development
    - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

install:
  - bash ./build/ci/install.sh

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bash ./build/ci/test.sh

addons:
  code_climate:
    repo_token: 149446817432cfe298a7cbade0632e7b406b7c6f931a086490f2222e998f7f52
